# -*- coding: utf-8 -*-
"""Survival_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/187Jq9dQVpI4z1SUOuDAKs3V2TNKCNUuS
"""

# Install required libraries
!pip install -U pandas-gbq lifelines google-cloud-bigquery --quiet

from google.colab import auth
auth.authenticate_user()

from google.cloud import bigquery
import pandas_gbq

project_id = "instacart-user-behavior"  # Replace with your actual project ID

query = """
SELECT
  user_id,
  segment_name,
  total_days,
  churned
FROM `Instacart_processed_data.user_survival_data_new`
"""

df = pandas_gbq.read_gbq(query, project_id=project_id)

from lifelines import KaplanMeierFitter
import matplotlib.pyplot as plt

# Initialize model
kmf = KaplanMeierFitter()

# Plot survival curve per segment
plt.figure(figsize=(10,6))
for segment in df['segment_name'].unique():
    data = df[df['segment_name'] == segment]
    kmf.fit(durations=data["total_days"], event_observed=data["churned"], label=segment)
    kmf.plot_survival_function()

plt.title("Survival Curve by User Segment")
plt.xlabel("Days Since First Order")
plt.ylabel("Survival Probability")
plt.grid(True)
plt.show()

from lifelines import CoxPHFitter
import pandas as pd

# Load data
df = pd.read_gbq("SELECT * FROM Instacart_processed_data.user_survival_data_new", project_id=project_id)

# One-hot encode 'segment_name'
df_encoded = pd.get_dummies(df, columns=['segment_name'], drop_first=True)

df_encoded = df_encoded.drop(columns=['max_gap'])

# Step 2: Add small regularization
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df_encoded, duration_col='total_days', event_col='churned')
cph.print_summary()
